from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='admin/')),
    url(r'^print_exercises_opt/$', 'student_manager.views.print_exercises_opt',
        name='print_exercises_opt'),
    url(r'^print_exercises/$', 'student_manager.views.print_exercises',
        name='print_exercises'),
    url(r'^print_exsheet_opt/$', 'student_manager.views.print_exsheet_opt',
        name='print_exsheet_opt'),
    url(r'^print_exsheet/$', 'student_manager.views.print_exsheet',
        name='print_exsheet'),
    url(r'^print_students_opt/$', 'student_manager.views.print_students_opt',
        name='print_students_opt'),
    url(r'^print_students/$', 'student_manager.views.print_students',
        name='print_students'),
    url(r'^print_groups_opt/$', 'student_manager.views.print_groups_opt',
        name='print_groups_opt'),
    url(r'^print_groups/$', 'student_manager.views.print_groups',
        name='print_groups'),
    url(r'^print_exams_opt/$', 'student_manager.views.print_exams_opt',
        name='print_exams_opt'),
    url(r'^print_exams/$', 'student_manager.views.print_exams',
        name='print_exams'),
    url(r'^import_exercises/$', 'student_manager.views.import_exercises',
        name='import_exercises'),
    url(r'^import_students/$', 'student_manager.views.import_students',
        name='import_students'),
    url(r'^import_registrations/$', 
        'student_manager.views.import_registrations',
        name='import_registrations'),
    url(r'^import_exams/$', 'student_manager.views.import_exams',
        name='import_exams'),
    url(r'^save_exam_results/$', 'student_manager.views.save_exam_results',
        name='save_exam_results'),
    url(r'^query_exams_opt/$', 'student_manager.views.query_exams_opt',
        name='query_exams_opt'),
    url(r'^query_exams/$', 'student_manager.views.query_exams',
        name='query_exams'),
    url(r'^query_regist/$', 'student_manager.views.query_regist',
        name='query_regist'),
    url(r'^query_assigned_groups/$', 
        'student_manager.views.query_assigned_groups',
        name='query_assigned_groups'),
    url(r'^export_students/$', 'student_manager.views.export_students',
        name='export_students'),
    url(r'^admin/', include(admin.site.urls)),
)
