from django.urls import re_path
from django.contrib import admin
from django.views.generic.base import RedirectView

from student_manager import views

admin.autodiscover()

urlpatterns = [
    re_path(r'^$', RedirectView.as_view(url='admin/', permanent=True)),
    re_path(r'^print_exercises_opt/$', views.print_exercises_opt,
        name='print_exercises_opt'),
    re_path(r'^print_exercises/$', views.print_exercises,
        name='print_exercises'),
    re_path(r'^print_exsheet_opt/$', views.print_exsheet_opt,
        name='print_exsheet_opt'),
    re_path(r'^print_exsheet/$', views.print_exsheet,
        name='print_exsheet'),
    re_path(r'^print_students_opt/$', views.print_students_opt,
        name='print_students_opt'),
    re_path(r'^print_students/$', views.print_students,
        name='print_students'),
    re_path(r'^print_groups_opt/$', views.print_groups_opt,
        name='print_groups_opt'),
    re_path(r'^print_groups/$', views.print_groups,
        name='print_groups'),
    re_path(r'^print_exams_opt/$', views.print_exams_opt,
        name='print_exams_opt'),
    re_path(r'^print_exams/$', views.print_exams,
        name='print_exams'),
    re_path(r'^import_exercises/$', views.import_exercises,
        name='import_exercises'),
    re_path(r'^import_students/$', views.import_students,
        name='import_students'),
    re_path(r'^import_registrations/$', views.import_registrations,
        name='import_registrations'),
    re_path(r'^import_exams/$', views.import_exams,
        name='import_exams'),
    re_path(r'^import_entrytests/$', views.import_entrytests,
        name='import_entrytests'),
    re_path(r'^save_exam_results/$', views.save_exam_results,
        name='save_exam_results'),
    re_path(r'^save_exercise_results/$', views.save_exercise_results,
        name='save_exercise_results'),
    re_path(r'^query_students_opt/$', views.query_students_opt,
        name='query_students_opt'),
    re_path(r'^query_students/$', views.query_students,
        name='query_students'),
    re_path(r'^query_exams_opt/$', views.query_exams_opt,
        name='query_exams_opt'),
    re_path(r'^query_exams/$', views.query_exams,
        name='query_exams'),
    re_path(r'^query_regist/$', views.query_regist,
        name='query_regist'),
    re_path(r'^query_new_assigned/$', views.query_new_assigned,
        name='query_new_assigned'),
    re_path(r'^query_exercise/$', views.query_exercise,
        name='query_exercise'),
    re_path(r'^export_students/$', views.export_students,
        name='export_students'),
    re_path(r'^query_examparts_opt/$', views.query_examparts_opt,
        name='query_examparts_opt'),
    re_path(r'^query_examparts/$', views.query_examparts,
        name='query_examparts'),
    re_path(r'^query_special_opt/$', views.query_special_opt,
        name='query_special_opt'),
    re_path(r'^query_special/$', views.query_special,
        name='query_special'),
    re_path(r'^export_entrytests/$', views.export_entrytests,
        name='export_entrytests'),
    re_path(r'^export_examresults/$', views.export_examresults,
        name='export_examresults'),
    re_path(r'^admin/', admin.site.urls),
]
