# Generated by Django 2.2.24 on 2021-10-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0002_auto_20210921_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytest',
            name='result',
            field=models.CharField(blank=True, choices=[('fail', 'fail'), ('pass', 'pass')], default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='assistent',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='time',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='time / group name (for import regist.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterexam',
            name='mark_limits',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterexam',
            name='part_points',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterexam',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(blank=True, choices=[('AN', 'AN'), ('ZU', 'ZU'), ('ST', 'ST'), ('HP', 'HP'), ('NP', 'NP')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='seat_map',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='value',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='obscured_matrikel',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='obscured'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
